version: '3.2'
services:
  rabbimq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
#    volumes:
#      - ~/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - network-net6
  api:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 80:80
      - 443:443
    networks:
      - network-net6
networks:
  network-net6:
    driver: bridge
